name: dev_dashboard


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - dev_backend_network
    restart: unless-stopped

  vexa-engine:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${ENGINE_API_PORT}:${ENGINE_API_PORT}"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - backend_venv:/app/.venv
      - backend_cache:/app/__pycache__
    networks:
      - dev_backend_network
    command: python main.py

    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    user: root

networks:
  dev_backend_network:
    driver: bridge

volumes:
  postgres_data_dev:
  backend_venv:
  backend_cache:
  redis_data:
  elasticsearch_data:



  #docker exec -it -u root multiassistant-vexa-backend-1 /bin/bash

  # docker exec -it -u root multiassistant-vexa-frontend-1 /bin/bash 