"""initial

Revision ID: 120a5a92fff0
Revises: 
Create Date: 2024-10-29 15:40:32.536968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '120a5a92fff0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_project',
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.UniqueConstraint('meeting_id', 'project_id', name='uq_meeting_project')
    )
    op.create_table('project_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("access_level IN ('removed', 'search', 'transcript')", name='valid_project_access_level'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user_share')
    )
    op.add_column('projects', sa.Column(
        'is_default',
        sa.Boolean(),
        nullable=False,
        server_default='false'
    ))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_user_default_project', 'projects', ['owner_id', 'is_default'], deferrable='True')
    op.alter_column('share_links', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('share_links', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_user_default_project', 'projects', type_='unique')
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('projects', 'is_default')
    op.drop_table('project_shares')
    op.drop_table('meeting_project')
    # ### end Alembic commands ###