"""add last_update and access_level to prompts

Revision ID: 16237b9f460b
Revises: 68e92a9378ef
Create Date: 2025-02-04 15:11:16.342350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16237b9f460b'
down_revision: Union[str, None] = '68e92a9378ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('last_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompts', sa.Column('access_level', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'access_level')
    op.drop_column('prompts', 'last_update')
    # ### end Alembic commands ###
