"""add_meeting_last_update

Revision ID: 2b0de27593ec
Revises: 812300fbc352
Create Date: 2024-11-26 17:51:21.702763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0de27593ec'
down_revision: Union[str, None] = '812300fbc352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('last_update', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'last_update')
    # ### end Alembic commands ###