"""add meeting_id to thread

Revision ID: 3b056f95afb1
Revises: 812300fbc352
Create Date: 2024-11-04 18:44:17.761769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b056f95afb1'
down_revision: Union[str, None] = '812300fbc352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('meeting_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'threads', 'meetings', ['meeting_id'], ['meeting_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'meeting_id')
    # ### end Alembic commands ###