"""add meeting name and summary columns

Revision ID: 812300fbc352
Revises: 4adebe2787f2
Create Date: 2024-11-02 23:05:07.667276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812300fbc352'
down_revision: Union[str, None] = '4adebe2787f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_name', sa.String(length=100), nullable=True))
    op.add_column('meetings', sa.Column('meeting_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'meeting_summary')
    op.drop_column('meetings', 'meeting_name')
    # ### end Alembic commands ###