"""add thread speaker association

Revision ID: ab5e92a47f33
Revises: abff3812a271
Create Date: 2024-12-09 19:53:09.237173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5e92a47f33'
down_revision: Union[str, None] = 'abff3812a271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_speaker',
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_speaker')
    # ### end Alembic commands ###