"""sharing

Revision ID: abff3812a271
Revises: 2b0de27593ec
Create Date: 2024-12-04 17:23:32.365578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abff3812a271'
down_revision: Union[str, None] = '2b0de27593ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_links', sa.Column('shared_meetings', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.alter_column('share_links', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('share_links', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('share_links', 'shared_meetings')
    # ### end Alembic commands ###